/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pralay;
@SuppressWarnings("all")
public class HEADER extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"HEADER\",\"namespace\":\"com.pralay\",\"fields\":[{\"name\":\"EVENT_ID\",\"type\":\"int\"},{\"name\":\"EVENT_VERSION\",\"type\":\"string\"},{\"name\":\"EVENT_TYPE\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"KEY\",\"type\":\"long\",\"default\":0}]}");
  public int EVENT_ID;
  public java.lang.CharSequence EVENT_VERSION;
  public java.lang.CharSequence EVENT_TYPE;
  public long KEY;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return EVENT_ID;
    case 1: return EVENT_VERSION;
    case 2: return EVENT_TYPE;
    case 3: return KEY;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: EVENT_ID = (java.lang.Integer)value$; break;
    case 1: EVENT_VERSION = (java.lang.CharSequence)value$; break;
    case 2: EVENT_TYPE = (java.lang.CharSequence)value$; break;
    case 3: KEY = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
